name: mlkit_translate
description: Translate text using Google ML Kit
version: 1.0.1+2
homepage: https://github.com/NickBalnaves/mlkit_translate

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.mlkit_translate
        pluginClass: MlkitTranslatePlugin
      ios:
        pluginClass: MlkitTranslatePlugin

